version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www/html
        container_name: app
    nignx:
      image: nginx:stable-alpine
      volumes:
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
          - ./:/var/www/html
      ports:
          - "8080:80"
      depends_on:
          - app
      container_name: nginx
    db:
      image: postgres:16.2-alpine
      restart: always
      container_name: postgres
      ports:
        - ${DB_PORT}:${DB_PORT}
      volumes:
        - postgres-db:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${DB_DATABASE}
        - POSTGRES_USER=${DB_USERNAME}
      depends_on:
        - app
volumes:
  postgres-db:
    external: false




